name: local_captcha
description: A fake captcha widget that helps speed up the development of prototype/demo app.
version: 1.0.5
homepage: https://github.com/kleong153
repository: https://github.com/kleong153/flutter-local-captcha
issue_tracker: https://github.com/kleong153/flutter-local-captcha/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
